name = "shred"
version = "0.2.1"
defaultTargets = ["SHRED", "lean-prefix-extract"]

[[require]]
name = "mathlib"
git = "https://github.com/xinhjBrant/mathlib4.git"
rev = "2f65ba7f1a9144b20c8e7358513548e317d26de1"

[[lean_lib]]
name = "SHRED"

[[lean_exe]]
name = "lean-prefix-extract"
root = "LeanPrefix.Extract"
supportInterpreter = true
